/// Catalogo de acciones del bridge ReaScript, extraido del bridge REAL.
///
/// **Generado, no escrito a mano.** Se extrae de
/// `%APPDATA%\\REAPER\\Scripts\\reaper_mcp_server.lua` con:
/// ```text
/// grep -oP 'function (\w+)\.(\w+)\s*\(' reaper_mcp_server.lua
/// ```
/// y se toma el segundo campo, que es la clave publica del handler.
///
/// Que se genere no es un detalle. La primera version de este catalogo
/// se escribio a mano, con nombres como `transport.setTempo` y `track.create`
/// con punto, y **ninguno existia**: el bridge responde `Unknown command:` y
/// las tres primeras pruebas contra Reaper real fallaron por eso.
///
/// Trampa del naming: el prefijo va **duplicado**. El bridge declara
/// `function fx.fx_add(p)` y la clave publica es `fx_add`, no `add`.
/// Lo mismo con `midi.midi_insert_note` -> `midi_insert_note`.
/// Cuando se actualice el bridge, hay que regenerar esto.
pub const ACTIONS: &[&str] = &[
    // add (1)
    "add_markers_batch",
    // analyze (1)
    "analyze_score",
    // chops (1)
    "chops_create_virtual_slice",
    // compose (3)
    "compose_arrangement",
    "compose_ensure_tracks",
    "compose_single_track",
    // configure (1)
    "configure_tracks",
    // edit (1)
    "edit_section",
    // envelope (3)
    "envelope_add_points",
    "envelope_clear_range",
    "envelope_get_points",
    // fx (18)
    "fx_add",
    "fx_disable",
    "fx_enable",
    "fx_get_chain",
    "fx_get_instrument",
    "fx_get_params",
    "fx_get_pin_mappings",
    "fx_get_preset",
    "fx_list_installed",
    "fx_move",
    "fx_navigate_preset",
    "fx_remove_batch",
    "fx_rename",
    "fx_scan_params",
    "fx_set_param",
    "fx_set_param_by_name",
    "fx_set_preset",
    "fx_show_ui",
    // get (1)
    "get_track_instruments",
    // item (22)
    "item_clone_to_position",
    "item_create_midi",
    "item_delete",
    "item_duplicate",
    "item_get_all",
    "item_get_info",
    "item_get_source_info",
    "item_insert_media",
    "item_move",
    "item_move_to_track",
    "item_select",
    "item_set_fade",
    "item_set_length",
    "item_set_mute",
    "item_set_volume",
    "item_split",
    "item_split_at_positions",
    "item_split_at_transients",
    "item_take_add",
    "item_take_delete_active",
    "item_take_list",
    "item_take_set_active",
    // items (1)
    "items_apply",
    // marker (6)
    "marker_add",
    "marker_add_region",
    "marker_delete",
    "marker_edit",
    "marker_get_all",
    "marker_go_to",
    // markers (1)
    "markers_apply",
    // midi (17)
    "midi_count_events",
    "midi_delete_all_notes",
    "midi_delete_cc",
    "midi_delete_note",
    "midi_get_note_names",
    "midi_get_notes",
    "midi_humanize",
    "midi_insert_cc",
    "midi_insert_note",
    "midi_insert_notes_batch",
    "midi_insert_program_change",
    "midi_list_programs",
    "midi_quantize",
    "midi_select_notes",
    "midi_set_item_extents",
    "midi_set_note",
    "midi_sort",
    // project (21)
    "project_backup",
    "project_export_audio",
    "project_get_change_count",
    "project_get_info",
    "project_get_metadata",
    "project_get_notes",
    "project_get_notes_info",
    "project_get_overview",
    "project_main_action",
    "project_new",
    "project_open",
    "project_redo",
    "project_save",
    "project_save_as",
    "project_set_grid",
    "project_set_metadata",
    "project_set_notes",
    "project_set_notes_info",
    "project_set_ripple_mode",
    "project_undo",
    "project_undo_group",
    // script (3)
    "script_list",
    "script_read_result",
    "script_run_start",
    // selection (9)
    "selection_deselect_all_items",
    "selection_deselect_all_tracks",
    "selection_get_selected_items",
    "selection_get_selected_tracks",
    "selection_get_time",
    "selection_select_all_items",
    "selection_select_all_tracks",
    "selection_set_loop",
    "selection_set_time",
    // send (8)
    "send_create",
    "send_get_all",
    "send_get_routing_diagram",
    "send_remove",
    "send_set_midi_channel",
    "send_set_mute",
    "send_set_pan",
    "send_set_volume",
    // setup (5)
    "setup_effect_bus",
    "setup_fx_chain",
    "setup_master_chain",
    "setup_routing",
    "setup_sidechain",
    // take (3)
    "take_set_pitch",
    "take_set_playrate",
    "take_set_reversed",
    // tempo (4)
    "tempo_add_marker",
    "tempo_clear_all",
    "tempo_delete_marker",
    "tempo_list_markers",
    // track (20)
    "track_create",
    "track_delete_batch",
    "track_freeze",
    "track_get_all",
    "track_get_info",
    "track_get_mixer_state",
    "track_get_peak",
    "track_get_state_chunk",
    "track_rename",
    "track_select",
    "track_set_color",
    "track_set_folder",
    "track_set_input",
    "track_set_mute",
    "track_set_pan",
    "track_set_record_arm",
    "track_set_solo",
    "track_set_state_chunk",
    "track_set_volume",
    "track_unfreeze",
    // transport (11)
    "transport_get_state",
    "transport_pause",
    "transport_play",
    "transport_record",
    "transport_set_bpm",
    "transport_set_playrate",
    "transport_set_position",
    "transport_set_time_signature",
    "transport_stop",
    "transport_toggle_metronome",
    "transport_toggle_repeat",
    // wipe (1)
    "wipe_all_midi",
];

/// Acciones agrupadas por prefijo, para `daw_catalog`.
pub const ACTION_GROUPS: &[(&str, &[&str])] = &[
    ("add", &[
        "add_markers_batch",
    ]),
    ("analyze", &[
        "analyze_score",
    ]),
    ("chops", &[
        "chops_create_virtual_slice",
    ]),
    ("compose", &[
        "compose_arrangement",
        "compose_ensure_tracks",
        "compose_single_track",
    ]),
    ("configure", &[
        "configure_tracks",
    ]),
    ("edit", &[
        "edit_section",
    ]),
    ("envelope", &[
        "envelope_add_points",
        "envelope_clear_range",
        "envelope_get_points",
    ]),
    ("fx", &[
        "fx_add",
        "fx_disable",
        "fx_enable",
        "fx_get_chain",
        "fx_get_instrument",
        "fx_get_params",
        "fx_get_pin_mappings",
        "fx_get_preset",
        "fx_list_installed",
        "fx_move",
        "fx_navigate_preset",
        "fx_remove_batch",
        "fx_rename",
        "fx_scan_params",
        "fx_set_param",
        "fx_set_param_by_name",
        "fx_set_preset",
        "fx_show_ui",
    ]),
    ("get", &[
        "get_track_instruments",
    ]),
    ("item", &[
        "item_clone_to_position",
        "item_create_midi",
        "item_delete",
        "item_duplicate",
        "item_get_all",
        "item_get_info",
        "item_get_source_info",
        "item_insert_media",
        "item_move",
        "item_move_to_track",
        "item_select",
        "item_set_fade",
        "item_set_length",
        "item_set_mute",
        "item_set_volume",
        "item_split",
        "item_split_at_positions",
        "item_split_at_transients",
        "item_take_add",
        "item_take_delete_active",
        "item_take_list",
        "item_take_set_active",
    ]),
    ("items", &[
        "items_apply",
    ]),
    ("marker", &[
        "marker_add",
        "marker_add_region",
        "marker_delete",
        "marker_edit",
        "marker_get_all",
        "marker_go_to",
    ]),
    ("markers", &[
        "markers_apply",
    ]),
    ("midi", &[
        "midi_count_events",
        "midi_delete_all_notes",
        "midi_delete_cc",
        "midi_delete_note",
        "midi_get_note_names",
        "midi_get_notes",
        "midi_humanize",
        "midi_insert_cc",
        "midi_insert_note",
        "midi_insert_notes_batch",
        "midi_insert_program_change",
        "midi_list_programs",
        "midi_quantize",
        "midi_select_notes",
        "midi_set_item_extents",
        "midi_set_note",
        "midi_sort",
    ]),
    ("project", &[
        "project_backup",
        "project_export_audio",
        "project_get_change_count",
        "project_get_info",
        "project_get_metadata",
        "project_get_notes",
        "project_get_notes_info",
        "project_get_overview",
        "project_main_action",
        "project_new",
        "project_open",
        "project_redo",
        "project_save",
        "project_save_as",
        "project_set_grid",
        "project_set_metadata",
        "project_set_notes",
        "project_set_notes_info",
        "project_set_ripple_mode",
        "project_undo",
        "project_undo_group",
    ]),
    ("script", &[
        "script_list",
        "script_read_result",
        "script_run_start",
    ]),
    ("selection", &[
        "selection_deselect_all_items",
        "selection_deselect_all_tracks",
        "selection_get_selected_items",
        "selection_get_selected_tracks",
        "selection_get_time",
        "selection_select_all_items",
        "selection_select_all_tracks",
        "selection_set_loop",
        "selection_set_time",
    ]),
    ("send", &[
        "send_create",
        "send_get_all",
        "send_get_routing_diagram",
        "send_remove",
        "send_set_midi_channel",
        "send_set_mute",
        "send_set_pan",
        "send_set_volume",
    ]),
    ("setup", &[
        "setup_effect_bus",
        "setup_fx_chain",
        "setup_master_chain",
        "setup_routing",
        "setup_sidechain",
    ]),
    ("take", &[
        "take_set_pitch",
        "take_set_playrate",
        "take_set_reversed",
    ]),
    ("tempo", &[
        "tempo_add_marker",
        "tempo_clear_all",
        "tempo_delete_marker",
        "tempo_list_markers",
    ]),
    ("track", &[
        "track_create",
        "track_delete_batch",
        "track_freeze",
        "track_get_all",
        "track_get_info",
        "track_get_mixer_state",
        "track_get_peak",
        "track_get_state_chunk",
        "track_rename",
        "track_select",
        "track_set_color",
        "track_set_folder",
        "track_set_input",
        "track_set_mute",
        "track_set_pan",
        "track_set_record_arm",
        "track_set_solo",
        "track_set_state_chunk",
        "track_set_volume",
        "track_unfreeze",
    ]),
    ("transport", &[
        "transport_get_state",
        "transport_pause",
        "transport_play",
        "transport_record",
        "transport_set_bpm",
        "transport_set_playrate",
        "transport_set_position",
        "transport_set_time_signature",
        "transport_stop",
        "transport_toggle_metronome",
        "transport_toggle_repeat",
    ]),
    ("wipe", &[
        "wipe_all_midi",
    ]),
];
