#!/usr/bin/env python3
"""Parsea la referencia oficial de la ReaScript API (REAPER v7.80) y la deja
en dos formatos:

1. `crates/heretic-daw/data/reaper-api.json` — las 730 funciones reales, con
   firma Lua, tipo de retorno y descripcion. Lo consume el MCP para que el
   agente pueda mirar la firma verdadera de cualquier funcion en vez de
   inventar parametros.

2. `docs/REAPER_API.md` — version compacta y curada, y sobre todo las tablas
   de PARAMETROS CON NOMBRE (D_VOL, B_MUTE, I_SOLO...), que son lo unico
   imposible de adivinar: un "D_VOL" mal puesto no da error, cambia otra cosa
   en silencio.

Por que la oficial y no el bridge ni la memoria:

- El doc lo genero REAPER v7.80, que es la version instalada.
- El bridge envuelve 162 de 730. Las 568 restantes son justamente las
  interesting para analisis y mastering (PCM_*, TimeMap, Nudge, Render...).
- Escribir de memoria los nombres de las 730 garantiza ~40 errores. Ya paso:
  documente `trackIndex` y son `track_index`; documente `op=volume` y no
  existe. Regla: si no esta en el fichero generado, no se inventa.

    python tools/gen_api_docs.py
"""
import html
import io
import json
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
DOC = os.path.join(ROOT, "reference", "reaper", "reascripthelp.html")
OUT_JSON = os.path.join(ROOT, "crates", "heretic-daw", "data", "reaper-api.json")

ENTRY = re.compile(
    r'<a name="(?P<name>[A-Za-z_0-9]+)"><hr></a>(?P<body>.*?)(?=<a name="|\Z)', re.S
)
LANG = re.compile(r'<div class="[a-z]_func">.*?</div>', re.S)
LUA = re.compile(r"<div class=\"l_func\">.*?<code>(?P<sig>.*?)</code>", re.S)
C = re.compile(r"<div class=\"c_func\">.*?<code>(?P<sig>.*?)</code>", re.S)
# Clave con nombre en la descripcion: "D_VOL : number : ..." / "B_MUTE : bool * : ..."
NAMED = re.compile(r"\b([A-Z][A-Z0-9_]{1,})\s*:\s*")
TAG = re.compile(r"<[^>]+>")


def clean(s):
    s = TAG.sub("", s)
    s = html.unescape(s).replace(" ", " ")
    return re.sub(r"\s+", " ", s).strip()


def named_params(desc):
    """Saca las claves con nombre de una descripcion.

    `SetMediaTrackInfo_Value` documenta sus ~50 claves en el texto plano, asi
    que el unico sitio fiable donde estan todas es aqui.
    """
    if not desc:
        return {}
    hits = list(NAMED.finditer(desc))
    out = {}
    for i, m in enumerate(hits):
        fin = hits[i + 1].start() if i + 1 < len(hits) else len(desc)
        out[m.group(1)] = desc[m.end():fin].strip(" .,")[:110]
    return out


def parse():
    src = io.open(DOC, encoding="utf-8", errors="replace").read()
    out = []
    for m in ENTRY.finditer(src):
        name, body = m.group("name"), m.group("body")
        lm = LUA.search(body)
        if not lm:
            continue  # no es funcion de la API: es un builtin eel_*
        sig = clean(lm.group("sig"))
        # La descripcion es lo que queda tras los bloques de firma.
        desc = clean(LANG.sub("", body))
        cm = C.search(body)
        # El tipo de retorno va en el prefijo de la firma Lua; si empieza
        # directamente por `reaper.` la funcion es void.
        pre = sig.split("reaper.")[0].strip() if "reaper." in sig else ""
        out.append(
            {
                "name": name,
                "lua": sig,
                "ret": pre or "void",
                "c": clean(cm.group("sig")) if cm else "",
                "desc": desc,
                "named": named_params(desc),
            }
        )
    return out


def main():
    if not os.path.exists(DOC):
        print("  falta %s" % DOC)
        print("  bajalo de https://www.reaper.fm/sdk/reascript/reascripthelp.html")
        return 1
    src = io.open(DOC, encoding="utf-8", errors="replace").read()
    fns = parse()
    if len(fns) < 500:
        print("  solo %d funciones parseadas: el formato del HTML cambio" % len(fns))
        return 1
    os.makedirs(os.path.dirname(OUT_JSON), exist_ok=True)
    io.open(OUT_JSON, "w", encoding="utf-8", newline="\n").write(
        json.dumps(
            {
                "version": (re.search(r"Generated by REAPER (v[\d.]+)", src) or [None, "?"])[1],
                "count": len(fns),
                "functions": fns,
            },
            ensure_ascii=False,
            indent=1,
            sort_keys=True,
        )
    )
    ver = re.search(r"Generated by REAPER (v[\d.]+)", src)
    n_named = sum(len(f["named"]) for f in fns)
    print("  %s -> %d funciones, %d claves con nombre  (%.0f KB)" % (
        ver.group(1), len(fns), n_named,
        os.path.getsize(OUT_JSON) / 1024))
    fam = {}
    for f in fns:
        fam[f["name"].split("_")[0]] = fam.get(f["name"].split("_")[0], 0) + 1
    print("  " + "  ".join("%s=%d" % kv for kv in
                           sorted(fam.items(), key=lambda x: -x[1])[:10]))
    return 0


if __name__ == "__main__":
    sys.exit(main())
